apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: osbpsql
  namespace: {{ .Release.Namespace | quote }}
spec:
  url: http://{{ template "osbpsql.fullname" . }}-osbpsql.{{ .Release.Namespace }}.svc.cluster.local:1338
  authInfo:
    basic:
      secretRef:
        name: {{ template "osbpsql.fullname" . }}-auth
        namespace: {{ .Release.Namespace | quote }}
