apiVersion: v1
kind: Secret
metadata:
  name: {{ template "osbpsql.fullname" . }}-secret
  namespace: default
type: Opaque
data:
  BASIC_AUTH_USERNAME: {{ b64enc .Values.basicAuth.username }}
  BASIC_AUTH_PASSWORD: {{ b64enc .Values.basicAuth.password }}
  DB_HOST: {{ b64enc .Values.db.host }}
  DB_PORT: {{ .Values.db.port | replace ":" "" | b64enc }}
  DB_USER: {{ b64enc .Values.db.user}}
  DB_PASSWORD: {{ b64enc .Values.db.password}}
  DB_DATABASE: {{ b64enc .Values.db.database}}
