apiVersion: v1
kind: Service
metadata:
  name: {{ template "osbpsql.fullname" . }}-osbpsql
  namespace: {{ .Release.Namespace | quote }}
  labels:
   app: {{ template "osbpsql.fullname" . }}
   chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
    - name: port-1338
      port: 1338
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ template "osbpsql.fullname" . }}